### ISSUE TITLE
Comments too dark.

### ISSUE THREAD

**Issue by oblitum** [romainl/Apprentice#11]
Hi, I realize colorscheme is mostly a taste thing, so no problems in closing this. Couldn't you set comments a bit brighter? I'm trying this colorscheme and it's quite nice except for this, I've tried it in two displays, a macbook and a LCD, in both the comments are a bit difficult to distinguish from background.

Thanks.

**Comment by romainl** [comment]
Well… yes, that color is *exactly* the one I want so I'll close this issue.

Thank you for trying Apprentice, though.

**Comment by oblitum** [comment]
Out of curiosity, is there an objective reason for that, I mean, you do enjoy comment text blurring with background?

**Comment by oblitum** [comment]
as-is, working at night with lower screen brightness, comments simply vanish.

**Comment by romainl** [comment]
I'm 40+ years old, I wear glasses, it's 11PM and I'm working at home with only a bit of ambient light on a late 2013 15" Retina MacBook Pro with the temperature of my display shifted to red by [f:lux](https://justgetflux.com/) and the brightness automatically lowered by the system to 75% from my preferred default of 87.5% because I'm not plugged in. Comments are perfectly readable and comfortable for me.

FWIW, you are not the first person to complain about the darkness of comments in Apprentice but I can see them very clearly so I see no reason to change their color. And… you can easily change that color yourself unlike with other trendy colorschemes:

* [256color & GUI](https://github.com/romainl/Apprentice/blob/master/colors/apprentice.vim#L42)
* [8/16color](https://github.com/romainl/Apprentice/blob/master/colors/apprentice.vim#L122)

**Comment by oblitum** [comment]
Ok. Got curious whether it's only looking good in Retina, mine is not one, only tried it in "normal" screens.

**Comment by romainl** [comment]
The Macbook belongs to my employer. My personal computer has been a tiny Mac Mini hooked to a lowly 19" display for a while and Apprentice looks just as good on it as on the Retina. And it looked just as good on the Windows PC I used for the two first weeks at my current job.

Maybe… you should get your eyes checked? Those computers really mess with our body.

**Comment by oblitum** [comment]
No!, I'm proud of my eyesight, I mean, seriously. I can read the comments fairly well in truth in ambient light, but it's a bit annoying to glance over them because of the low contrast, it's more of a feeling than incapacity of reading. But, I have an habit of working at night with the lowest brightness possible, when my eyes get comfortable with lack of light. In this condition it simply doesn't work, at last for me (if you have gone through the same and still there's no problem for you, then, or my eyes are not quite ok or you have super-eyesight).

**Comment by romainl** [comment]
One level above black screen is pretty hardcore.

If you are doing that to preserve your eyeballs I **highly** suggest the aforelinked "f:lux": it shifts the temperature of your screen *progressively* toward red during the night. It's really awesome once you pass the initial "weird" phase.

**Comment by oblitum** [comment]
Thanks for the tip. In truth I already have experience with "f:lux", I've used it before for quite some time but stopped because it made me want to sleep. I'll get back to it when I get back a normal routine.

**Comment by oblitum** [comment]
ah... I got used to it... I enjoy it now xD
