### ISSUE TITLE
Does Vim-Polyglot plugin makes Apprentice better? 

### ISSUE THREAD

**Issue by HicaroD** [romainl/Apprentice#63]
It's just a question. I love this colorscheme and I want to know if any Vim plugin for syntax highlighting changes something using this colorscheme? If it doesn't, close my issue. Thanks for the attention!

**Comment by romainl** [comment]
Ideally, syntax authors are supposed to link their custom groups to default syntax groups so that colorschemes only have to deal with the default syntax groups. That way, defining any syntax group for any filetype is almost 100% guaranteed to be transparent for any competently written colorscheme:

- `colors/foo.vim` handles default `Comment` group
- `syntax/quux.vim` defines `QuuxBoom` group and links it to default `Comment` group
- `colors/foo.vim` automatically handles `QuuxBoom` because it handles default `Comment` group

Apprentice generally honours that mechanism, with only a few filetype-specific exceptions that I find quite reasonable, so syntax scripts that honour that mechanism should work well with it, too. But, if `syntax/quux.vim` defines `QuuXBoom` without linking it to some default group, then that group will simply be ignored by Apprentice.

The onus is therefore on syntax authors to ensure that their custom groups are properly linked to default groups if they want colorschemes to handle their language properly, *not* on colorscheme authors to handle every special case under the sun.
